name: pwd_reservation_app
description: "Bus Reservation App dedicated for PWDs."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.0.0
  flutter_secure_storage: ^4.2.1
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  http_interceptor: ^2.0.0-beta.8
  image: ^3.2.2
  carousel_slider: ^4.0.0
  file_picker: ^5.2.4
  http_parser: ^4.0.2
  image_picker: ^1.1.1
  flutter_ringtone_player: ^4.0.0+2
  flutter_osm_plugin: ^0.70.4
  scrollable_positioned_list: ^0.3.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
